// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IYieldStrategy$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IYieldStrategy";
  readonly sourceName: "src/interfaces/IYieldStrategy.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"asset","type":"address"}],"name":"currentApyBps","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"deposit","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"}],"name":"totalValue","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"address","name":"recipient","type":"address"}],"name":"withdraw","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/interfaces/IYieldStrategy.sol";
  readonly buildInfoId: "solc-0_8_24-fc4fc52c8710d43b3be047e03683b90a29386b95";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IYieldStrategy"]: IYieldStrategy$Type;
    ["src/interfaces/IYieldStrategy.sol:IYieldStrategy"]: IYieldStrategy$Type;
  }
}