// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IAaveV3Pool$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IAaveV3Pool";
  readonly sourceName: "src/interfaces/IAaveV3Pool.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"address","name":"onBehalfOf","type":"address"},{"internalType":"uint16","name":"referralCode","type":"uint16"}],"name":"supply","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"address","name":"to","type":"address"}],"name":"withdraw","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/interfaces/IAaveV3Pool.sol";
  readonly buildInfoId: "solc-0_8_24-fc4fc52c8710d43b3be047e03683b90a29386b95";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IAaveV3Pool"]: IAaveV3Pool$Type;
    ["src/interfaces/IAaveV3Pool.sol:IAaveV3Pool"]: IAaveV3Pool$Type;
  }
}